version: '3'

services:
  api:
    image: api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./api/:/api
    env_file:
      - ./api/.env 
    networks:
      - mynetwork

  client:
    build: ./client
    environment:
      PORT: 3031
    ports:
      - "3031:3031"
    volumes:
      - ./client/public:/client/public
      - ./client/src:/client/src
    networks:
      - mynetwork

networks:
  mynetwork:
