version: '3'

services:
  api:
    image: api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 6000:6000
    volumes:
      - ./api/:/api

  client:
    build: ./client
    environment:
      PORT: 3031
    ports:
      - "3031:3031"
    volumes:
      - ./client/public:/client/public
      - ./client/src:/client/src

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    command: mongod --bind_ip_all
    ports:
      - 5432:5432
    volumes:
      - ./mongo_data:/data/db
