version: '3'

services:
  api:
    image: api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./api/:/api
    env_file:
      - ./api/src/.env 
    networks:
      - mynetwork

  client:
    build: ./client
    environment:
      PORT: 3031
    ports:
      - "3031:3031"
    volumes:
      - ./client/public:/client/public
      - ./client/src:/client/src
    networks:
      - mynetwork

  # mongodb:
  #   image: mongo:latest
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=admin
  #     - MONGO_INITDB_ROOT_PASSWORD=admin
  #   command: mongod --bind_ip_all
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ./mongo_data:/data/db
  #   networks:
  #     - mynetwork

networks:
  mynetwork:
